### ISSUE TITLE
ChangeString() might introduce wild pointers?

### ISSUE THREAD

**Issue by GittyupMule** [gcevans/StringHolder#2]
Pending the writing of a test case, because I don't know how pull requests work.

It looks like, since c-strings are arrays (always passed by pointer), that you could run this

```cpp
int main() {
    char* string = "Hello World!";
    for (int i = 0; i < 1; i++) {
        StringHolder holder("another string");
        holder.ChangeString(string);
    }
    // holder goes out of scope, destructor deletes its string
    std::cout << string; // Wild pointer, this will fail
    return 0;
}
```

**Comment by gcevans** [comment]
While this code will fail it is not an error in the StringHolder class. You are keeping a pointer to an memory held by an object and using it after the object is destroyed. This is a bug in the code you wrote. It does show on of the key challenges in C++. That is tracking and managing the lifetimes of objects in memory.

Actually I did not read your code carefully enough. I will look at it later but nothing in the StringHolder class is changing the string variable.

**Comment by gcevans** [comment]
Ok reviewing it this morning the only issue with the above code is that the type you need for string is const `char*` not `char*` and in the old days that would not even have been an issue. The pointer in that you are worried about is just fine.
